### ISSUE TITLE
This error occurs when running the command

### ISSUE THREAD

**Issue by liujiadong369** [facebookresearch/segment-anything#137]
Traceback (most recent call last):
  File "E:\project\segment-anything-main\scripts\amg.py", line 238, in <module>
    main(args)
  File "E:\project\segment-anything-main\scripts\amg.py", line 221, in main
    masks = generator.generate(image)
  File "E:\project\segment-anything-main\venv\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "e:\project\segment-anything-main\segment_anything\automatic_mask_generator.py", line 164, in generate
    mask_data = self._generate_masks(image)
  File "e:\project\segment-anything-main\segment_anything\automatic_mask_generator.py", line 210, in _generate_masks
    crop_data = self._process_crop(image, crop_box, layer_idx, orig_size)
  File "e:\project\segment-anything-main\segment_anything\automatic_mask_generator.py", line 242, in _process_crop
    self.predictor.set_image(cropped_im)
  File "e:\project\segment-anything-main\segment_anything\predictor.py", line 60, in set_image
    self.set_torch_image(input_image_torch, image.shape[:2])
  File "E:\project\segment-anything-main\venv\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "e:\project\segment-anything-main\segment_anything\predictor.py", line 89, in set_torch_image
    self.features = self.model.image_encoder(input_image)
  File "E:\project\segment-anything-main\venv\lib\site-packages\torch\nn\modules\module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "e:\project\segment-anything-main\segment_anything\modeling\image_encoder.py", line 112, in forward
    x = blk(x)
  File "E:\project\segment-anything-main\venv\lib\site-packages\torch\nn\modules\module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "e:\project\segment-anything-main\segment_anything\modeling\image_encoder.py", line 174, in forward
    x = self.attn(x)
  File "E:\project\segment-anything-main\venv\lib\site-packages\torch\nn\modules\module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "e:\project\segment-anything-main\segment_anything\modeling\image_encoder.py", line 234, in forward
    attn = add_decomposed_rel_pos(attn, q, self.rel_pos_h, self.rel_pos_w, (H, W), (H, W))
  File "e:\project\segment-anything-main\segment_anything\modeling\image_encoder.py", line 358, in add_decomposed_rel_pos
    attn.view(B, q_h, q_w, k_h, k_w) + rel_h[:, :, :, :, None] + rel_w[:, :, :, None, :]
RuntimeError: CUDA out of memory. Tried to allocate 1024.00 MiB (GPU 0; 6.00 GiB total capacity; 4.60 GiB already allocated; 0 bytes free; 4.67 GiB reserved in total by PyTorch)

**Comment by derekray311511** [comment]
It seems that your gpu is out of memory. Maybe try a smaller image as input?

**Comment by liujiadong369** [comment]
Now I'm using a 90kb image

**Comment by widedh** [comment]
Hello, I have the same issue. Did you find a solution? Thank you

**Comment by Leci37** [comment]
I have done some reverse engineering, 
You have to try the different combinations of  `dtype `(`dtype=` has multiple combinations, look the code https://github.com/pytorch/pytorch/blob/main/torch/nn/modules/module.py )  Also `non_blocking `combination
Example: `torch.float16, torch.float32, torch.float64, torch.half, torch.cdouble, torch.complex128 ...`) : 
```python
sam = sam_model_registry[KEY_model_type](checkpoint=sam_checkpoint)
gpu1 = torch.device("cuda:1")
sam.to(gpu1, dtype=torch.half, non_blocking=True)
```

It also helps to change the **_max_split_size_mb_**, also try different combinations. 
Example: `512, 256,128....`
```python
import os
os.environ['PYTORCH_CUDA_ALLOC_CONF']='max_split_size_mb:512' #'garbage_collection_threshold:0.8,max_split_size_mb:512'
```

It may also help to clear the cache at startup. 
```python
import torch
#https://stackoverflow.com/questions/59129812/how-to-avoid-cuda-out-of-memory-in-pytorch
torch.cuda.empty_cache()
torch.cuda.memory_summary(device=None, abbreviated=False)
import gc
gc.collect()
```

**FINALLY** , **_if nothing works_**,  if you have a very small GPU (2gb) you have to **switch it to CPU**. take 3min per image but works 
```python
device = "cpu" # "cuda"
sam = sam_model_registry[KEY_model_type](checkpoint=sam_checkpoint)
sam.to(device=device)
```
