### ISSUE TITLE
use in kaggle notebook

### ISSUE THREAD

**Issue by deno-source** [facebookresearch/segment-anything#345]
Loading model...
Traceback (most recent call last):
  File "/kaggle/working/segment-anything/scripts/amg.py", line 238, in <module>
    main(args)
  File "/kaggle/working/segment-anything/scripts/amg.py", line 198, in main
    _ = sam.to(device=args.device)
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1145, in to
    return self._apply(convert)
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 797, in _apply
    module._apply(fn)
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 797, in _apply
    module._apply(fn)
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 797, in _apply
    module._apply(fn)
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 820, in _apply
    param_applied = fn(param)
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1143, in convert
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
  File "/opt/conda/lib/python3.10/site-packages/torch/cuda/__init__.py", line 239, in _lazy_init
    raise AssertionError("Torch not compiled with CUDA enabled")
AssertionError: Torch not compiled with CUDA enabled

**Comment by deno-source** [comment]
kaggle is working, But on my local mac computer, it still reported the error

**Comment by snowsky** [comment]
Can add `--device cpu` to `amp.py` command line :)
