### ISSUE TITLE
Unexpected token 'h', "html>

### ISSUE THREAD

**Issue by huzhenhong** [facebookresearch/segment-anything#416]
Unexpected token 'h', "html>
<htm"... is not valid JSON
SyntaxError: Unexpected token 'h', "html>
<htm"... is not valid JSON
    at JSON.parse (<anonymous>)
    at npyjs.parse (http://localhost:8080/main.js:39291:29)
    at npyjs.load (http://localhost:8080/main.js:39319:29)
    at async loadNpyTensor (http://localhost:8080/main.js:36261:25)

the demo folder nothing have modify but MODEL_DIR,
and my node version is v18.12.0

**Comment by sanbuphy** [comment]
the same

**Comment by abinash-kumar** [comment]
@sanbuphy @sanbuphy  please check your network tab you will get some fetch call and that call must be getting failed to fetch 

you guys need add all the files and the try to run the project 

![image](https://github.com/facebookresearch/segment-anything/assets/28887343/85bed6c9-07ec-4da5-89dc-3ce1a78f962f)

**IMAGE_PATH** This is the image path 
**IMAGE_EMBEDDING** This file has all the embedding information and it will be different for different image 
**MODEL_DIR** This is SAM model it can remain same

**Comment by huzhenhong** [comment]
@abinash-kumar 
thanks, i use the sam_vit_b_01ec64.pth to generate "dogs_embedding.npy", no it works

btw, is the demo only support hover mode?

**Comment by wxjttxs** [comment]
> sam_vit_b_01ec64

hello, where did you download this checkpoint? could you show me this link? thank you so much.

**Comment by gwyanCN** [comment]
> @abinash-kumar thanks, i use the sam_vit_b_01ec64.pth to generate "dogs_embedding.npy", no it works
> 
> btw, is the demo only support hover mode?

the same question

**Comment by RemyNtshaykolo** [comment]
using 
```ts
const IMAGE_PATH = "src/assets/data/dogs_embedding.png";
const IMAGE_EMBEDDING = "src/assets/data/dogs_embedding.npy";
```
fixed the error. Basically, the file where not found and an html error file was returned.
