### ISSUE TITLE
error occurs in python scritps

### ISSUE THREAD

**Issue by YuhaoShan2018** [facebookresearch/segment-anything#47]
1st :masks,_, _ = predictor.predict('bed')

AssertionError: point_labels must be supplied if point_coords is supplied.

2ed: from segment_anything import build_sam, SamAutomaticMaskGenerator
mask_generator = SamAutomaticMaskGenerator(build_sam(checkpoint=pth_path))
masks = mask_generator_generate(img)
NameError: name 'mask_generator_generate' is not defined

how to deal with that ques?

**Comment by samuggi** [comment]
mask_generator_generate ->mask_generator.generate is done!

**Comment by elbriga** [comment]
Traceback (most recent call last):
  File "/home/gabriel/workspace/MASKs/makeMasks.py", line 4, in <module>
    masks = mask_generator.generate('chevette.jpg')
  File "/home/gabriel/.local/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/gabriel/.local/lib/python3.10/site-packages/segment_anything/automatic_mask_generator.py", line 163, in generate
    mask_data = self._generate_masks(image)
  File "/home/gabriel/.local/lib/python3.10/site-packages/segment_anything/automatic_mask_generator.py", line 198, in _generate_masks
    orig_size = image.shape[:2]
AttributeError: 'str' object has no attribute 'shape'

**Comment by elbriga** [comment]
AttributeError: 'str' object has no attribute 'shape'
Could not get it to work

**Comment by NeuroLord** [comment]
> 

Has anyone solved this problem? I too have a 'str' object that has no 'shape' attribute. No idea how to deal with it. Help

**Comment by NeuroLord** [comment]
> AttributeError: 'str' object has no attribute 'shape' Could not get it to work

Has anyone solved this problem? I too have a 'str' object that has no 'shape' attribute. No idea how to deal with it. Help

**Comment by elbriga** [comment]
seams like the object should be a numpi, but is a string, anyone?

**Comment by xinkangzhou** [comment]
> 像对象这样的接缝应该是一个 numpi，但是是一个字符串，有人吗？

img = cv2.imread("notebooks/images/dog.jpg")
img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
predictor.set_image(img)

**Comment by wgsthink** [comment]
> seams like the object should be a numpi, but is a string, anyone?

it's a NumPy array of an image

**Comment by NTUZZH** [comment]
Should use cv2.imread() to load the image, this way will solve the problem saying " AttributeError: 'str' object has no attribute 'shape' "
