### ISSUE TITLE
Kernal crashes in example notebook.

### ISSUE THREAD

**Issue by aboharbf** [facebookresearch/segment-anything#513]
Trying to run on local machine, seems to hit some problem just going through the example notebook. when trying to plot after downloading the dog image. the image is loaded successfully, but the subsequent cell complains about the kernal dying. Screenshot and Jupyter log below.

![image](https://github.com/facebookresearch/segment-anything/assets/25850560/0a8690c3-168e-43c2-b51a-31559e382181)

```
16:03:37.106 [info] Handle Execution of Cells 2,5,6,8,9,11,12,15,17,19,21,24,25,26,27,28 for c:\Track-Anything\automatic_mask_generator_example.ipynb
16:03:37.113 [info] Kernel acknowledged execution of cell 2 @ 1691352217111
16:03:37.131 [info] End cell 2 execution @ 1691352217130, started @ 1691352217111, elapsed time = 0.019s
16:03:37.134 [info] Kernel acknowledged execution of cell 5 @ 1691352217131
16:03:37.147 [info] End cell 5 execution @ 1691352217146, started @ 1691352217131, elapsed time = 0.015s
16:03:37.155 [info] Kernel acknowledged execution of cell 6 @ 1691352217148
16:03:37.162 [info] End cell 6 execution @ 1691352217161, started @ 1691352217148, elapsed time = 0.013s
16:03:37.165 [info] Kernel acknowledged execution of cell 8 @ 1691352217163
16:03:39.137 [info] End cell 8 execution @ 1691352219134, started @ 1691352217163, elapsed time = 1.971s
16:03:39.142 [info] Kernel acknowledged execution of cell 9 @ 1691352219138
16:03:39.150 [info] End cell 9 execution @ 1691352219149, started @ 1691352219138, elapsed time = 0.011s
16:03:39.152 [info] Kernel acknowledged execution of cell 11 @ 1691352219151
16:03:39.165 [info] End cell 11 execution @ 1691352219164, started @ 1691352219151, elapsed time = 0.013s
16:03:39.167 [info] Kernel acknowledged execution of cell 12 @ 1691352219166
16:03:39.234 [warn] StdErr from Kernel Process OMP: Error #15: Initializing libiomp5md.dll, but found libiomp5md.dll already initialized.
OMP: Hint This means that multiple copies of the OpenMP runtime have been linked into the program. That is dangerous, since it can degrade performance or cause incorrect results. The best thing to do is to ensure that only a single OpenMP runtime is linked into the process, e.g. by avoiding static linking of the OpenMP runtime in any library. As an unsafe, unsupported, undocumented workaround you can set the environment variable KMP_DUPLICATE_LIB_OK=TRUE to allow the program to continue to execute, but that may cause crashes or silently produce incorrect results. For more information, please see http://www.intel.com/software/products/support/.
16:03:39.837 [error] Disposing session as kernel process died ExitCode: 3, Reason: OMP: Error #15: Initializing libiomp5md.dll, but found libiomp5md.dll already initialized.
OMP: Hint This means that multiple copies of the OpenMP runtime have been linked into the program. That is dangerous, since it can degrade performance or cause incorrect results. The best thing to do is to ensure that only a single OpenMP runtime is linked into the process, e.g. by avoiding static linking of the OpenMP runtime in any library. As an unsafe, unsupported, undocumented workaround you can set the environment variable KMP_DUPLICATE_LIB_OK=TRUE to allow the program to continue to execute, but that may cause crashes or silently produce incorrect results. For more information, please see http://www.intel.com/software/products/support/.

16:03:39.837 [info] Dispose Kernel process 11932.
16:03:39.837 [error] Raw kernel process exited code: 3
16:03:39.838 [error] Error in waiting for cell to complete [Error: Canceled future for execute_request message before replies were done
	at t.KernelShellFutureHandler.dispose (c:\Users\<username>\.vscode\extensions\ms-toolsai.jupyter-2023.7.1002162226-win32-x64\out\extension.node.js:2:32375)
	at c:\Users\<username>\.vscode\extensions\ms-toolsai.jupyter-2023.7.1002162226-win32-x64\out\extension.node.js:2:51427
	at Map.forEach (<anonymous>)
	at y._clearKernelState (c:\Users\<username>\.vscode\extensions\ms-toolsai.jupyter-2023.7.1002162226-win32-x64\out\extension.node.js:2:51412)
	at y.dispose (c:\Users\<username>\.vscode\extensions\ms-toolsai.jupyter-2023.7.1002162226-win32-x64\out\extension.node.js:2:44894)
	at c:\Users\<username>\.vscode\extensions\ms-toolsai.jupyter-2023.7.1002162226-win32-x64\out\extension.node.js:24:114648
	at ae (c:\Users\<username>\.vscode\extensions\ms-toolsai.jupyter-2023.7.1002162226-win32-x64\out\extension.node.js:2:1588852)
	at rv.dispose (c:\Users\<username>\.vscode\extensions\ms-toolsai.jupyter-2023.7.1002162226-win32-x64\out\extension.node.js:24:114624)
	at sv.dispose (c:\Users\<username>\.vscode\extensions\ms-toolsai.jupyter-2023.7.1002162226-win32-x64\out\extension.node.js:24:117994)
	at process.processTicksAndRejections (node:internal/process/task_queues:96:5)]
16:03:39.838 [warn] Cell completed with errors {
  message: 'Canceled future for execute_request message before replies were done'
}
16:03:39.838 [info] End cell 12 execution @ 1691352219838, started @ 1691352219166, elapsed time = 0.672s
16:03:39.839 [warn] Cancel all remaining cells due to cancellation or failure in execution
16:03:39.839 [info] End cell 15 execution @ undefined, started @ undefined, elapsed time = 0s
16:03:39.839 [info] End cell 17 execution @ undefined, started @ undefined, elapsed time = 0s
16:03:39.839 [info] End cell 19 execution @ undefined, started @ undefined, elapsed time = 0s
16:03:39.839 [info] End cell 21 execution @ undefined, started @ undefined, elapsed time = 0s
16:03:39.839 [info] End cell 24 execution @ undefined, started @ undefined, elapsed time = 0s
16:03:39.839 [info] End cell 25 execution @ undefined, started @ undefined, elapsed time = 0s
16:03:39.839 [info] End cell 26 execution @ undefined, started @ undefined, elapsed time = 0s
16:03:39.839 [info] End cell 27 execution @ undefined, started @ undefined, elapsed time = 0s
16:03:39.839 [info] End cell 28 execution @ undefined, started @ undefined, elapsed time = 0s
16:03:39.883 [info] End cell 12 execution @ undefined, started @ undefined, elapsed time = 0s
```

**Comment by salykovaa** [comment]
Hi @aboharbf, I have the same problem. Did you solve it?

**Comment by Kuha-i** [comment]
Any fix on this? Im having the same issue

**Comment by timonpalm** [comment]
Having the same issue but in the cell where you execute the generate function

**Comment by MarianaParrinha** [comment]
Hello, I am facing the same issue... does anyone know how to solve this??
