### ISSUE TITLE
Error:  A load persistent id instruction was encountered, but no persistent_load function was specified.

### ISSUE THREAD

**Issue by dayunbao** [facebookresearch/segment-anything#564]
I'm integrating Segment Anything into an app I'm building, and am calling the automatic generation via an API.  But I am getting this error:
```
 A load persistent id instruction was encountered, but no persistent_load function was specified.
 Traceback (most recent call last):
 File "/home/ec2-user/.local/share/virtualenvs/stable-diffusion-webui-c31KCnbi/lib/python3.10/site-packages/anyio/streams/memory.py", line 98, in receive
 return self.receive_nowait()
 File "/home/ec2-user/.local/share/virtualenvs/stable-diffusion-webui-c31KCnbi/lib/python3.10/site-packages/anyio/streams/memory.py", line 93, in receive_nowait
 raise WouldBlock
 anyio.WouldBlock
 During handling of the above exception, another exception occurred:
 Traceback (most recent call last):
 File "/home/ec2-user/.local/share/virtualenvs/stable-diffusion-webui-c31KCnbi/lib/python3.10/site-packages/starlette/middleware/base.py", line 78, in call_next
 message = await recv_stream.receive()
 File "/home/ec2-user/.local/share/virtualenvs/stable-diffusion-webui-c31KCnbi/lib/python3.10/site-packages/anyio/streams/memory.py", line 118, in receive
 raise EndOfStream
 anyio.EndOfStream
 During handling of the above exception, another exception occurred:
 Traceback (most recent call last):
 File "/home/ec2-user/Code/comic_creator/stable-diffusion-webui/modules/api/api.py", line 195, in exception_handling
 return await call_next(request)
 File "/home/ec2-user/.local/share/virtualenvs/stable-diffusion-webui-c31KCnbi/lib/python3.10/site-packages/starlette/middleware/base.py", line 84, in call_next
 raise app_exc
 File "/home/ec2-user/.local/share/virtualenvs/stable-diffusion-webui-c31KCnbi/lib/python3.10/site-packages/starlette/middleware/base.py", line 70, in coro
 await self.app(scope, receive_or_disconnect, send_no_error)
 File "/home/ec2-user/.local/share/virtualenvs/stable-diffusion-webui-c31KCnbi/lib/python3.10/site-packages/starlette/middleware/base.py", line 108, in __call__
 response = await self.dispatch_func(request, call_next)
 File "/home/ec2-user/Code/comic_creator/stable-diffusion-webui/modules/api/api.py", line 155, in log_and_time
 res: Response = await call_next(req)
 File "/home/ec2-user/.local/share/virtualenvs/stable-diffusion-webui-c31KCnbi/lib/python3.10/site-packages/starlette/middleware/base.py", line 84, in call_next
 raise app_exc
 File "/home/ec2-user/.local/share/virtualenvs/stable-diffusion-webui-c31KCnbi/lib/python3.10/site-packages/starlette/middleware/base.py", line 70, in coro
 await self.app(scope, receive_or_disconnect, send_no_error)
 File "/home/ec2-user/.local/share/virtualenvs/stable-diffusion-webui-c31KCnbi/lib/python3.10/site-packages/starlette/middleware/cors.py", line 84, in __call__
 await self.app(scope, receive, send)
 File "/home/ec2-user/.local/share/virtualenvs/stable-diffusion-webui-c31KCnbi/lib/python3.10/site-packages/starlette/middleware/gzip.py", line 24, in __call__
 await responder(scope, receive, send)
 File "/home/ec2-user/.local/share/virtualenvs/stable-diffusion-webui-c31KCnbi/lib/python3.10/site-packages/starlette/middleware/gzip.py", line 44, in __call__
 await self.app(scope, receive, self.send_with_gzip)
 File "/home/ec2-user/.local/share/virtualenvs/stable-diffusion-webui-c31KCnbi/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
 raise exc
 File "/home/ec2-user/.local/share/virtualenvs/stable-diffusion-webui-c31KCnbi/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
 await self.app(scope, receive, sender)
 File "/home/ec2-user/.local/share/virtualenvs/stable-diffusion-webui-c31KCnbi/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
 raise e
 File "/home/ec2-user/.local/share/virtualenvs/stable-diffusion-webui-c31KCnbi/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
 await self.app(scope, receive, send)
 File "/home/ec2-user/.local/share/virtualenvs/stable-diffusion-webui-c31KCnbi/lib/python3.10/site-packages/starlette/routing.py", line 718, in __call__
 await route.handle(scope, receive, send)
 File "/home/ec2-user/.local/share/virtualenvs/stable-diffusion-webui-c31KCnbi/lib/python3.10/site-packages/starlette/routing.py", line 276, in handle
 await self.app(scope, receive, send)
 File "/home/ec2-user/.local/share/virtualenvs/stable-diffusion-webui-c31KCnbi/lib/python3.10/site-packages/starlette/routing.py", line 66, in app
 response = await func(request)
 File "/home/ec2-user/.local/share/virtualenvs/stable-diffusion-webui-c31KCnbi/lib/python3.10/site-packages/fastapi/routing.py", line 237, in app
 raw_response = await run_endpoint_function(
 File "/home/ec2-user/.local/share/virtualenvs/stable-diffusion-webui-c31KCnbi/lib/python3.10/site-packages/fastapi/routing.py", line 165, in run_endpoint_function
 return await run_in_threadpool(dependant.call, **values)
 File "/home/ec2-user/.local/share/virtualenvs/stable-diffusion-webui-c31KCnbi/lib/python3.10/site-packages/starlette/concurrency.py", line 41, in run_in_threadpool
 return await anyio.to_thread.run_sync(func, *args)
 File "/home/ec2-user/.local/share/virtualenvs/stable-diffusion-webui-c31KCnbi/lib/python3.10/site-packages/anyio/to_thread.py", line 33, in run_sync
 return await get_asynclib().run_sync_in_worker_thread(
 File "/home/ec2-user/.local/share/virtualenvs/stable-diffusion-webui-c31KCnbi/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
 return await future
 File "/home/ec2-user/.local/share/virtualenvs/stable-diffusion-webui-c31KCnbi/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 807, in run
 result = context.run(func, *args)
 File "/home/ec2-user/Code/comic_creator/stable-diffusion-webui/extensions/sd-webui-segment-anything/api/api.py", line 37, in automatic_generation
 return automatic_mask_generation(**request_body.dict())
 File "/home/ec2-user/Code/comic_creator/stable-diffusion-webui/extensions/sd-webui-segment-anything/segment_anything_lib/automatic_generation.py", line 41, in automatic_mask_generation
 sam = sam_model_registry[model_type](checkpoint=sam_checkpoint)
 File "/home/ec2-user/.local/share/virtualenvs/stable-diffusion-webui-c31KCnbi/lib/python3.10/site-packages/segment_anything/build_sam.py", line 15, in build_sam_vit_h
 return _build_sam(
 File "/home/ec2-user/.local/share/virtualenvs/stable-diffusion-webui-c31KCnbi/lib/python3.10/site-packages/segment_anything/build_sam.py", line 105, in _build_sam
 state_dict = torch.load(f)
 File "/home/ec2-user/Code/comic_creator/stable-diffusion-webui/modules/safe.py", line 108, in load
 return load_with_extra(filename, *args, extra_handler=global_extra_handler, **kwargs)
 File "/home/ec2-user/Code/comic_creator/stable-diffusion-webui/modules/safe.py", line 156, in load_with_extra
 return unsafe_torch_load(filename, *args, **kwargs)
 File "/home/ec2-user/.local/share/virtualenvs/stable-diffusion-webui-c31KCnbi/lib/python3.10/site-packages/torch/serialization.py", line 815, in load
 return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
 File "/home/ec2-user/.local/share/virtualenvs/stable-diffusion-webui-c31KCnbi/lib/python3.10/site-packages/torch/serialization.py", line 1033, in _legacy_load
 magic_number = pickle_module.load(f, **pickle_load_args)
 _pickle.UnpicklingError: A load persistent id instruction was encountered, but no persistent_load function was specified.
```
This is the output of `pip list` from within the virtual environment I'm using:
```
Package                 Version
----------------------- ------------------
absl-py                 1.4.0
accelerate              0.21.0
addict                  2.4.0
aenum                   3.1.12
aiofiles                23.1.0
aiohttp                 3.8.4
aiosignal               1.3.1
altair                  5.0.1
antlr4-python3-runtime  4.9.3
anyio                   3.7.0
async-timeout           4.0.2
attrs                   23.1.0
basicsr                 1.4.2
beautifulsoup4          4.12.2
blendmodes              2022
boltons                 23.0.0
cachetools              5.3.1
certifi                 2023.5.7
cffi                    1.15.1
charset-normalizer      3.1.0
clean-fid               0.1.35
click                   8.1.3
clip                    1.0
cmake                   3.26.4
contourpy               1.1.0
cssselect2              0.7.0
cycler                  0.11.0
deprecation             2.1.0
einops                  0.4.1
exceptiongroup          1.1.1
facexlib                0.3.0
fastapi                 0.94.0
ffmpy                   0.3.0
filelock                3.12.2
filterpy                1.4.5
flatbuffers             23.5.26
fonttools               4.40.0
frozenlist              1.3.3
fsspec                  2023.6.0
ftfy                    6.1.1
future                  0.18.3
fvcore                  0.1.5.post20221221
gdown                   4.7.1
gfpgan                  1.3.8
gitdb                   4.0.10
GitPython               3.1.32
google-auth             2.20.0
google-auth-oauthlib    1.0.0
gradio                  3.41.2
gradio_client           0.5.0
grpcio                  1.54.2
h11                     0.12.0
httpcore                0.15.0
httpx                   0.24.1
huggingface-hub         0.15.1
idna                    3.4
imageio                 2.31.1
importlib-metadata      6.7.0
importlib-resources     6.0.1
inflection              0.5.1
iopath                  0.1.9
Jinja2                  3.1.2
jsonmerge               1.8.0
jsonschema              4.17.3
kiwisolver              1.4.4
kornia                  0.6.7
lark                    1.1.2
lazy_loader             0.2
lightning-utilities     0.8.0
linkify-it-py           2.0.2
lit                     16.0.6
llvmlite                0.40.1
lmdb                    1.4.1
lpips                   0.1.4
lxml                    4.9.2
Markdown                3.4.3
markdown-it-py          2.2.0
MarkupSafe              2.1.3
matplotlib              3.7.1
mdit-py-plugins         0.3.3
mdurl                   0.1.2
mediapipe               0.10.1
mpmath                  1.3.0
multidict               6.0.4
networkx                3.1
numba                   0.57.1
numpy                   1.23.5
oauthlib                3.2.2
omegaconf               2.2.3
open-clip-torch         2.20.0
opencv-contrib-python   4.7.0.72
opencv-python           4.8.0.76
orjson                  3.9.1
packaging               23.1
pandas                  2.0.2
piexif                  1.1.3
Pillow                  9.5.0
pip                     23.1.2
platformdirs            3.7.0
portalocker             2.7.0
protobuf                3.20.0
psutil                  5.9.5
pyasn1                  0.5.0
pyasn1-modules          0.3.0
pycparser               2.21
pydantic                1.10.9
pydub                   0.25.1
Pygments                2.15.1
pyparsing               3.1.0
pyrsistent              0.19.3
PySocks                 1.7.1
python-dateutil         2.8.2
python-multipart        0.0.6
pytorch-lightning       1.9.4
pytz                    2023.3
PyWavelets              1.4.1
PyYAML                  6.0
realesrgan              0.3.0
regex                   2023.6.3
reportlab               4.0.4
requests                2.31.0
requests-oauthlib       1.3.1
resize-right            0.0.2
rsa                     4.9
safetensors             0.3.1
scikit-image            0.21.0
scipy                   1.10.1
segment-anything        1.0
semantic-version        2.10.0
sentencepiece           0.1.99
setuptools              67.8.0
six                     1.16.0
smmap                   5.0.0
sniffio                 1.3.0
sounddevice             0.4.6
soupsieve               2.4.1
starlette               0.26.1
svglib                  1.5.1
sympy                   1.12
tabulate                0.9.0
tb-nightly              2.14.0a20230621
tensorboard-data-server 0.7.1
termcolor               2.3.0
tifffile                2023.4.12
timm                    0.9.2
tinycss2                1.2.1
tokenizers              0.13.3
tomesd                  0.1.3
tomli                   2.0.1
toolz                   0.12.0
torch                   2.0.1+cu118
torchdiffeq             0.2.3
torchmetrics            0.11.4
torchsde                0.2.5
torchvision             0.15.2+cu118
tqdm                    4.65.0
trampoline              0.1.2
transformers            4.30.2
triton                  2.0.0
typing_extensions       4.6.3
tzdata                  2023.3
uc-micro-py             1.0.2
urllib3                 1.26.16
uvicorn                 0.22.0
wcwidth                 0.2.6
webencodings            0.5.1
websockets              11.0.3
Werkzeug                2.3.6
wheel                   0.40.0
xformers                0.0.20
yacs                    0.1.8
yapf                    0.40.1
yarl                    1.9.2
zipp                    3.15.0
```
I can call Segment Anything from the command line (the amg script), and it works.  It's only failing when I try to call it via the API I've built.

**Comment by dongshaojia** [comment]
Did you solve it, I had the same problem, can you help me
